[project]
name = "bid-compare"
version = "0.1.0"
description = "Tool for analyzing and comparing construction bid data from multiple CSVs."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
]
